---
- name: Install logstash
  hosts: logstash
  become: yes

  tasks:
    - name: Импорт ключа репозитория ELK
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present
    - name: Добавление репозитория ELK
      apt_repository:
        repo:
          "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
        state: present
        filename: elk
    - name: Обновление списка пакетов
      apt:
        update_cache: yes
  
   #  Install and Config Logstash
    - name: install logstash
      package:
        name: logstash
        state: present
    - name: Config logstash
      copy:
        src: ./configs/logstash/pipelines.yml
        dest: /etc/logstash/pipelines.yml
    - name: Config logstash pipeline
      copy:
        src: ./configs/logstash/beat_nginx.conf
        dest: /etc/logstash/conf.d/beat_nginx.conf
    - name: запуск EL
      service:
        name: logstash
        state: restarted
