---
- name: Установка и настройка Nginx, Zabbix Agent2, Filebeat на веб-серверы
  hosts: webservers
  become: yes

  tasks:
    - name: Обновление списка пакетов
      apt:
        update_cache: yes
    - name: Установка Nginx
      package:
        name: nginx
        state: present
    - name: Запуск Nginx
      service:
        name: nginx
        state: started
        enabled: yes


    - name: Импорт ключа репозитория Zabbix
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present
    - name: Добавление репозитория Zabbix
      apt_repository:
        repo:
          "deb http://repo.zabbix.com/zabbix/7.0/ubuntu jammy main"
        state: present
        filename: zabbix
    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка Zabbix Agent2
      package:
        name: zabbix-agent2
        state: present

    - name: Настройка конфигурации Zabbix Agent2
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server=127.0.0.1'
        line: 'Server=zabbix.ru-central1.internal'

    - name: Перезапуск Zabbix Agent2
      service:
        name: zabbix-agent2
        state: restarted


    - name: Импорт ключа репозитория ELK
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present
    - name: Добавление репозитория ELK
      apt_repository:
        repo:
          "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
        state: present
        filename: elk
    - name: Обновление списка пакетов
      apt:
        update_cache: yes
    - name: Установка Filebeat
      package:
        name: filebeat
        state: present
    - name: Настройка Filebeat
      copy:
        src: ./configs/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
    - name: запуск Filebeat
      service:
        name: filebeat
        state: restarted
