---
- name: Установка и настройка Zabbix Server
  hosts: zabbix
  become: yes

  tasks:
    - name: Импорт ключа репозитория Zabbix
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present
    - name: Добавление репозитория Zabbix
      apt_repository:
        repo:
          "deb http://repo.zabbix.com/zabbix/7.0/ubuntu jammy main"
        state: present
        filename: zabbix
    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка Zabbix сервера, веб-интерфейса и агента
      package:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
    - name: Установка PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Создание базы данных
      shell: |
        su - postgres -c 'psql --command "CREATE USER zabbix WITH PASSWORD '\'password\'';"' /
        su - postgres -c 'psql --command "CREATE DATABASE zabbix OWNER zabbix;"' /
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: Настройка конфигурации Zabbix Server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=password'

    - name: Настройка конфигурации Ngninx (listen)
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: '^ *# *listen *[0-9]+;'
        line: 'listen 8080;'
        
    - name: Настройка конфигурации Ngninx (server_name)
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: '^ *# *server_name *(([a-z]*)?([0-9]*)?.?)*;'
        line: 'server_name example.com;'
    - name: Перезапуск сервисов
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - postgresql
        - zabbix-server
        - nginx
        - php8.1-fpm
        - zabbix-agent
